server:
  port: ${PORT:8081}
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 10
      min-spare: 2
    max-connections: 50

spring:
  application:
    name: manufacturing-erp-backend
  main:
    lazy-initialization: true
  jmx:
    enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Munna@74}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expirationMs: ${JWT_EXPIRATION_MS:86400000} # 24 hours

aws:
  s3:
    endpoint: ${AWS_ENDPOINT_URL_S3:https://br-wild-mouse-ay4uil0a.storage.c-5.us-east-2.aws.neon.tech}
    access-key: ${AWS_ACCESS_KEY_ID:nak_live_b107441c21b442bf95396813bb82cd53}
    secret-key: ${AWS_SECRET_ACCESS_KEY:nsk_live_1a9f296d539216bfcd9531c6586b9333d52c6ad84645177a6943b8be7af7317c}
    region: ${AWS_REGION:us-east-2}
    bucket: ${AWS_S3_BUCKET:msme-erp-storage}

logging:
  level:
    root: INFO
    com.msme.erp: INFO
    org.springframework.security: WARN


